sudo: false
language: go
go:
  - "1.11"
go_import_path: github.com/andig/ingress
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
env:
  global:
    - PATH=/home/travis/gopath/bin:$PATH
    # docker credentials
    - secure: "yC560/fwwPCfl749/XaZqiQPvq/lw+gLQ33oYj+76krAnERDYbpluzdIvMttwX386/gj4rSZb8ZiH55cYQ71tmILwgjAT8Yt7sKLLACNrVHXRUYkgKaizBANpnP7iPTF3EnBXuOafON/qO5vm0nxAYSowYYNWLYhSlUP3p6cutGBhJeKJvV4I3VIrfK2A2Ogzhv7m5nJQ0y1tRi0kZXGm+h3jrVOlob4/DOBVf4ZpomaRH/hAvYoNh8RBLKdgRqqiAydkbLh1REa0jOltTeVjkkBgNlGM8mlF0WfbzJAxxwQbBaKmvjcVTHdRAasy4GsVB4l8s+o6XGB/KxrTV90IGMbhF3xlAbiz4nnYrhLTXacf2Z7CnBUr+Cb+pOc62eSrXPk8pjOedAEYCPrIhPdQ8B/d3jumsJrhbdT8SpSQ2y3KEoDuKdDc2HTav6MFZkhY6wR7/zgfNQnIrvBZD+DN4Fx7xUOlOiEz4EgyYTQ5U5ImBE2th7iVi3/5NUgkmAx1pqbrt3gZnwclynW7bjYkPZp7lKwLdAtCx81tNwJpKK7B9ciO5yHFUpSEsQWI50BbVOIfpviBlGn8C5DjcLir5bpNDbwmZBChaGP6AugeWFQeaEM2heO5H5UriV/e2WOSuJ4y3FiPuScNiOJiY0bwDfKSuOqn6hp46zwyASj6dw="
    - secure: "wimZqQcYNlrjzzwBjKHmjbrK4TXOQWCQgAGVmfae3205URlLqNKEnGogFz578R0IeGG0v83etjU7za1I9M3nlBb5Bd+uH2XA7UbdDPSrU+VbKMOPgqztD9BsuvzBlqOf3zkTwkwBoxofodyF78ZIXX7ZgR2ljzkHIcsMeRM4IIMZMmM4OhZ+xHG1g4OSOx6FEMSzCYrcmMpJpFF9rYjVkC4Pp1A3llEltGA49JMFePE3Rp6Xuq4Yhfzg8Bjct7XZPs7Dv2sNM9kiyD5riWlyj7htV6WcpQNMRrvfIwtCkeaz2/Zi22Xyf2SN7+H+eufTnE1UKjog2BI/OecC0bFDDfB9t9zSmOk2MB7ziNIbEH2lBATlmrUj/3x/ptakgANR2LkBsKfmz16KUAKFeAP8ovdiKF9++OjojwWubYDfMrRAkEQJzESJCVkCCvpISdfDNKyp3MokW2lu8bUgy8Brtkc2606X5Khq+4ZmMkudK2YVk38ER7pLkzrAsu6ViKjJwGAn1F359XLkWvLFb5bkvrGmZdnj6CpW5tKuvT269PO/uGUAy8rWvCauG0WTaOwyEOsx4WM7DkLn3Kca75s6Xw54fNi+XvB7x6Fnzch94hk0yh71y+ZJdmgdR3TZIM8La5ePcFAGooPyFX6WvyDcTjG7sgxoNRJSq/LVROFRGAg="
    - secure: "nCmPCDWIc6Y0KlG2W3eMeKa/ItkAoHC10Lq8ijoD4SNS3/VCV7zR4Mjm/FZeHmNl1eHG5tyoUuJHxvey1ULyTNN3iFrvNy+KOWJ4vzfsTp/kPgBWqb/KrSeDdfmT4y8By1OWoptaSzYPhuCnbGxtjzLQSs8GKzwZ4UA/1tzf7wuAPzsreZ+Q33xFPAXYcnpMzbZza1OTLhnZlgV9JeR/uhACPScvSovgLt4W9qYmJwwgP+26uqrFTnB7tywPqOquH6503/5bCHjgwjCGSjgEUHCzop/AlWdl25+0oBNs57DClRHymUeyP3guJv8A1QYK5qDUrkChAyrdIU1lhAlWa3sw+xhjqZiKHkTKdp0fxFxOzzjzLs6nwWWvL3sGid62SnLXfCVKrVdGEhtr8ekGVFjmBzn1evvlqXTbhE6HrDl6MbZiVc8KVaosh5OAVrWwqNupCu+nSNV12z36cQkCivLAGtZsluhMgBDkJzYWaAtSSqaTp684fK50gRsntf3iP3v5CFbRyfGeOI2JVANYwjOKDRsBNWL2GIYhRbxwPGKwk/00wHhjG1h9juJhx2Z8CWkOMDbrZvvjfKWNwv/U/FM2fB9Db6XbxOOCCNW55UHg69UJUyfNof8/FWJKKx9XLXvcekCcxVEZEMXlTYrbk6qDO4sg1wqdN1UnF5JHgPA="
    - COMMIT=${TRAVIS_COMMIT::8}
before_script:
  - export GO111MODULE=on
script:
  - make all
  - make test
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=andig/ingress
  - docker pull $REPO:latest
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then 
      docker build --cache-from $REPO:latest -f Dockerfile -t $REPO:$COMMIT .
      docker tag $REPO:$COMMIT $REPO:latest
      docker push $REPO
    fi
