sudo: false
language: go
go:
  - "1.11"
  - "master"
go_import_path: github.com/andig/ingress
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_script:
  - export GO111MODULE=on
script:
  - make all
  - make test
