# Sources and targets describe a list of source and target datasources.
# All data sources are uniquely identified by their name.
#
# Valid source types:
# - telemetry (internal runtime data)
# - homie
# - mqtt (planned)
sources:
- name: telemetry
  type: telemetry
- name: homie
  type: homie
  url: tcp://localhost:1883
- name: mqtt-sub
  type: mqtt
  url: tcp://localhost:1883
  topic: input/#

# Valid target types:
# - volkszaehler
# - volkszaehler-push (planned)
targets:
- name: vz
  type: volkszaehler
  url: https://demo.volkszaehler.org/
- name: mqtt-pub
  type: mqtt
  url: tcp://localhost:1883
  topic: source1/node/%name%

# Wires connect data sources with targets. Mapping rules can be assigned to a wire.
wires:
- sources: 
  - homie
  - mqtt-sub
  targets: 
  - vz
  - mqtt-pub
  mappings:
  - direct
  - namemapping2

# Mappings configure which source topic is mapped to which target topics
# Mappings are reusable across wirings
mappings:
- name: direct
  entries:
  - source: zaehlerstand
    target: foobar
