# Input and output describe a list of input/output datasources.
# All data sources are uniquely identified by their name.
#
# Valid input types:
# - homie
# - mqtt (planned)
input:
- name: homie
  type: homie
  # url: tcp://localhost:1883
  url: tcp://test.mosquitto.org:1883
- name: mqtt
  type: mqtt
  # url: tcp://localhost:1883
  url: tcp://test.mosquitto.org:1883

# Valid output types:
# - volkszaehler
# - volkszaehler-push (planned)
output:
- name: volkszaehler
  type: volkszaehler
  url: https://demo.volkszaehler.org/
  
# Wiring configures how input and output data sources are connected.
# Goal of the wiring is to connect input and output data sources.
# Multiple mappings can be assigned to a single wiring. If no mapping is defined,
# the "auto" mapping is applied. Auto mapping works by matching topic names.
wiring:
- input: 
  - homie
  - mqtt
  output: 
  - volkszaehler
  mapping:
  - direct
  - namemapping2

# Mapping configures which input topic is mapped to which output topics
# Mappings are reusable across wirings
mapping:
- name: direct
  entries:
  - source: zaehlerstand
    target: foobar
