# Input and output describe a list of input/output datasources.
# All data sources are uniquely identified by their name.
#
# Valid input types:
# - homie
# - mqtt (planned)
input:
- name: homie
  type: homie
  # url: tcp://localhost:1883
  url: tcp://localhost:1883
- name: mqtt-sub
  type: mqtt
  # url: tcp://localhost:1883
  url: tcp://localhost:1883

# Valid output types:
# - volkszaehler
# - volkszaehler-push (planned)
output:
- name: volkszaehler
  type: volkszaehler
  url: https://demo.volkszaehler.org/
- name: mqtt-pub
  type: mqtt
  # url: tcp://localhost:1883
  url: tcp://localhost:1883
  topic: homie/output/node/%id%%name%

# Wiring configures which input and output data sources are connected.
# Multiple mappings can be assigned to a single wiring. If no mapping is defined,
# the "auto" mapping is applied. Auto mapping works by matching topic names.
wiring:
- input: 
  - homie
  - mqtt-sub
  output: 
  - volkszaehler
  - mqtt-pub
  mapping:
  - direct
  - namemapping2

# Mapping configures which input topic is mapped to which output topics
# Mappings are reusable across wirings
mapping:
- name: direct
  entries:
  - source: zaehlerstand
    target: foobar
